it-at-m/opensource.muenchen.de

.github/workflows/deploy.yml
.vitepress/config.mts

Deploy to github pages when commiting to main-branch

:sparkles: github action to deploy to github pages

---

.vitepress/config.mts
.vitepress/theme/index.ts
package-lock.json
package.json

Adds vuetify as a dependency so we can use it's components

:sparkles: add vuetify to vitepress

---

.vitepress/components/TagTile.vue

switched to vuetify card-component for nicer design and fix link-generation with base-url
**Reference**
⚠️ depends on #14 - please merge first
closes #8

8 links to toolssoftware broken

---

.vitepress/config.mts

impress link in html template uses base path, fix #36

---

.vitepress/components/TagTile.vue
.vitepress/software-de.data.js

Use two data loaders and use them according to the current language.
**Reference**
closes #61

:bug: fix excerpts in wrong language

---

.github/workflows/docker-publish.yml

see issue
**Reference**
Issues #83

:sparkles: only build new image when on main branch

---

de/software/openapi-generator.md
de/software/robotframework.md
public/color-logo.svg
software/openapi-generator.md

Openapi generator

---

.github/workflows/docker-publish.yml

reduce actions to one job
**Reference**
Issues #108

reduce actions to one job

---

.vitepress/config.mts
de/software/robotframework.md
software/robotframework.md

add geodata and windows client

---

.vitepress/config.mts
nginx.rewriteslashes.conf

**Reference**
Issues #136 #104

using .html again

---

de/use.md
use.md

"Wir nutzen freie Software wo immer möglich!" is not citeable

use better quote with cite

---

de/software/kiwi.md
software/kiwi.md

added explanation unicode
**Reference**
Issues https://github.com/it-at-m/UnicodeEingabeKiwi2/issues/4

Kiwiunicode

---

de/software/robotframework.md
software/robotframework.md

robotframework sponsor

---

de/publish.md
publish.md

publiccode

---

de/software/keepass.md
software/keepass.md

keepass verbose

---

.vitepress/config.mts

assets.muenchen.de

---

.vitepress/config.mts
de/ospo.md
de/sabbatical.md
ospo.md
sabbatical.md

Short description or comments
**Reference**
Issues #XXX

sabbatical from internal wiki

---

de/software/mucgpt.md
software/mucgpt.md

Wrong Pictures were displayed for the Brainstorming Feature of MUCGPT.

updated Pictures

---

de/software/zammad.md
software/zammad.md

zammad DBS

---

de/improve.md
de/sabbatical.md
improve.md
sabbatical.md

sabbatical improve

---

de/software/zammad.md
software/zammad.md

zammad-ldap-sync

---

.vitepress/components/TagTile.vue
de/use.md
use.md

Regarding https://git.muenchen.de/ccse/ospo/-/issues/429#note_830565 (internal link)
Please test locally - first checks where successfull.

:sparkles: add new exclude-prop for TagTile.vue

---

de/software/zammad.md
software/zammad.md

zammad-BayernID

---

de/software/mucgpt.md
software/mucgpt.md

- Removed ChatGPT-3.5 from the description
- instead it can use any OpenAI-Compatible API
-  Doesn't contain any azure IAC files
- FastAPI instead of Quart.

🎈 update mucgpt description. Remove azure stuff

---

de/in-house-development.md
in-house-development.md

refarch link github

---

.vitepress/components/TagTile.vue
de/use.md
use.md

Short description or comments
**Reference**
Issues #XXX

Exclude tags v2

---

de/sabbatical.md
sabbatical.md

sabbatical projects more specific

sabbatical projects more specific

---

.vitepress/config.mts
de/repositories.md
repositories.md

repositories

---

de/sabbatical.md
de/software/integreat.md
sabbatical.md
software/integreat.md

integreat open-source-sabbatical

integreat open-source-sabbatical

---

de/software/zammad.md
software/zammad.md

add Kontaktformular Stadtkämmerei
**Reference**
Issues #XXX

Kontaktformular Stadtkämmerei

---

.vitepress/components/SoftwareImageAvatar.vue
package-lock.json
package.json

Fix #179: square icons are weirdly cropped

---

.vitepress/components/SoftwareImageAvatar.vue
.vitepress/theme/lhm.css
de/software/consul.md
software/consul.md

white background also in dark mode for transparent icons #305

---

de/fossaas.md
fossaas.md
public/fossaas-venn.svg

Fossaas venn again

---

de/publish.md
publish.md

right-from-the-start

---

de/software/integreat.md
software/integreat.md

Innovationspreis muenchen

---

de/software/dave.md
software/dave.md

add https://github.com/orgs/it-at-m/projects/14/

https://github.com/orgs/it-at-m/projects/14/

---

de/software/elster-nezo_plugin.md
software/elster-nezo_plugin.md

clarification: its a keycloak plugin

clarification: its a keycloak plugin

---

.vitepress/theme/lhm.css

*  official rit colors 
**Reference**
Issues #338

official rit cicd

---

de/usability-analysis.md
de/use.md
usability-analysis.md
use.md

Development usabilty

---

de/usability-analysis.md
usability-analysis.md

If commercial support is not available

no support

---

de/software/integreat.md
software/integreat.md

Add further information about integreat chat to integreat.md in german and english.

add new information to integreat.md

---

de/fossaas.md
de/software/consul.md
de/software/mucgpt.md
de/software/openstreetmap.md
fossaas.md
software/consul.md
software/mucgpt.md
software/openstreetmap.md

fossaas apps

---

de/software/isi.md
de/software/mdas.md
software/isi.md
software/mdas.md

use search link for multirepos

multirepos search link

---

.vitepress/components/EscapeGame.vue
.vitepress/theme/LhmThemeExtension.vue

The site has not yet had a good 404 treatment. Users had no idea how to get back to the main page. 
**Solution** 
the widespread industry standard is that not only is the user redirected, but he must first prove his eligibility by completing a game. An example for this behavior can be seen at https://ki.muenchen.de/404

Proper 404 handling

---

.vitepress/theme/enhancements/i18n/lang/de.ts
.vitepress/theme/enhancements/i18n/lang/en.ts
de/software/checkmk.md
de/software/grafana.md
de/software/graylog.md
de/software/openshift.md
software/checkmk.md
software/grafana.md
software/graylog.md
software/openshift.md

add tag observability

---

de/principles.md
principles.md

add https://floss-pso.network/public-sector-ospos/

public-sector-ospos

---

de/software/nvda.md
software/nvda.md

Update nvda.md in german and english concerning sponsoring amount

update nvda.md concerning sponsoring amount

---

README.md
de/usability-analysis.md
usability-analysis.md

usability-analysis: Doku 
**Reference**
Issues #344

usability-analysis: Doku 

---

de/sabbatical.md
de/software/integreat.md
sabbatical.md

add sabbatical final report in integreat.md

add sabbatical final report 

---

de/software/nvda.md
software/nvda.md

adding link to muenchen.digital regarding sponsoring nv access

adding link to muenchen.digital

---

de/usability-analysis.md
usability-analysis.md

criterium api
